# Generated by Django 3.2.3 on 2021-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bought_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('today_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
