# Generated by Django 3.2.3 on 2021-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='sold',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='sale_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='today_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
