# Generated by Django 3.2.3 on 2021-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_detail', '0002_auto_20210530_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='bought_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
