# Generated by Django 3.2.4 on 2021-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_detail', '0003_auto_20210601_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='share',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='today_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
